# Generated by Django 3.2.6 on 2021-08-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myname', '0002_auto_20210819_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
